SET TIME ZONE 'UTC';

CREATE TABLE IF NOT EXISTS schema_migrations (
    version INTEGER PRIMARY KEY,
    filename TEXT NOT NULL UNIQUE,
    checksum TEXT NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_user_id BIGINT NOT NULL UNIQUE,
    display_name TEXT,
    timezone TEXT NOT NULL DEFAULT 'UTC',
    personal_profile JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_chat_id BIGINT NOT NULL UNIQUE,
    chat_type TEXT NOT NULL CHECK (chat_type IN ('private', 'group')),
    title TEXT,
    group_profile JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_whitelisted BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    silent_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat_members (
    chat_id BIGINT NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role TEXT NOT NULL DEFAULT 'member',
    participant_profile JSONB NOT NULL DEFAULT '{}'::jsonb,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMPTZ,
    PRIMARY KEY (chat_id, user_id)
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    telegram_message_id BIGINT NOT NULL,
    reply_to_message_id BIGINT,
    text TEXT,
    message_type TEXT NOT NULL DEFAULT 'text',
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ,
    CONSTRAINT messages_chat_telegram_message_unique UNIQUE (chat_id, telegram_message_id)
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT NOT NULL UNIQUE,
    telegram_update_id BIGINT UNIQUE,
    event_type TEXT NOT NULL,
    scope_type TEXT NOT NULL CHECK (scope_type IN ('personal', 'group')),
    scope_id TEXT NOT NULL,
    actor_user_id TEXT,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'retry', 'failed')),
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    available_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS memory_cards (
    id TEXT PRIMARY KEY,
    scope_type TEXT NOT NULL CHECK (scope_type IN ('personal', 'group')),
    scope_id TEXT NOT NULL,
    memory_type TEXT NOT NULL,
    subject_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    subject_keys TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    summary TEXT NOT NULL CHECK (length(btrim(summary)) > 0),
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    importance DOUBLE PRECISION NOT NULL CHECK (importance BETWEEN 0 AND 1),
    confidence DOUBLE PRECISION NOT NULL CHECK (confidence BETWEEN 0 AND 1),
    freshness DOUBLE PRECISION NOT NULL CHECK (freshness BETWEEN 0 AND 1),
    status TEXT NOT NULL DEFAULT 'candidate' CHECK (status IN ('candidate', 'active', 'archived', 'superseded', 'rejected')),
    origin TEXT NOT NULL CHECK (origin IN ('explicit', 'inferred', 'system')),
    pinned BOOLEAN NOT NULL DEFAULT FALSE,
    usage_policy JSONB NOT NULL DEFAULT '{"assist": true, "callback": true, "roast": false, "proactive": false}'::jsonb,
    evidence JSONB NOT NULL DEFAULT '[]'::jsonb,
    source_count INTEGER NOT NULL DEFAULT 0 CHECK (source_count >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_confirmed_at TIMESTAMPTZ,
    last_used_at TIMESTAMPTZ,
    valid_from TIMESTAMPTZ,
    valid_until TIMESTAMPTZ,
    superseded_by TEXT REFERENCES memory_cards(id) ON DELETE SET NULL,
    CONSTRAINT memory_cards_valid_window CHECK (valid_until IS NULL OR valid_from IS NULL OR valid_until >= valid_from)
);

CREATE TABLE IF NOT EXISTS memory_relations (
    id TEXT PRIMARY KEY,
    scope_type TEXT NOT NULL CHECK (scope_type IN ('personal', 'group')),
    scope_id TEXT NOT NULL,
    from_memory_id TEXT NOT NULL REFERENCES memory_cards(id) ON DELETE CASCADE,
    relation_type TEXT NOT NULL,
    to_memory_id TEXT NOT NULL REFERENCES memory_cards(id) ON DELETE CASCADE,
    weight DOUBLE PRECISION NOT NULL DEFAULT 1 CHECK (weight BETWEEN 0 AND 1),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT memory_relations_not_self CHECK (from_memory_id <> to_memory_id),
    CONSTRAINT memory_relations_unique UNIQUE (from_memory_id, relation_type, to_memory_id)
);

CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type TEXT NOT NULL CHECK (scope_type IN ('personal', 'group')),
    scope_id TEXT NOT NULL,
    owner_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    title TEXT NOT NULL CHECK (length(btrim(title)) > 0),
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'completed', 'cancelled')),
    due_at TIMESTAMPTZ,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type TEXT NOT NULL CHECK (scope_type IN ('personal', 'group')),
    scope_id TEXT NOT NULL,
    target_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    due_at TIMESTAMPTZ NOT NULL,
    recurrence_rule TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'sent', 'cancelled', 'retry', 'failed')),
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    last_fired_at TIMESTAMPTZ,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS interventions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT REFERENCES events(event_id) ON DELETE SET NULL,
    scope_type TEXT NOT NULL CHECK (scope_type IN ('personal', 'group')),
    scope_id TEXT NOT NULL,
    primary_action TEXT NOT NULL CHECK (primary_action IN ('ignore', 'reply', 'act', 'schedule')),
    mode TEXT,
    intervention_score DOUBLE PRECISION CHECK (intervention_score IS NULL OR intervention_score BETWEEN 0 AND 100),
    reason_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
    policy_version TEXT NOT NULL,
    selected_memory_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    generated_text TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS feedback_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    intervention_id BIGINT REFERENCES interventions(id) ON DELETE SET NULL,
    scope_id TEXT NOT NULL,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    feedback_type TEXT NOT NULL,
    value DOUBLE PRECISION,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dedupe_key TEXT NOT NULL UNIQUE,
    channel TEXT NOT NULL,
    destination_id TEXT NOT NULL,
    payload JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'sent', 'retry', 'failed')),
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    available_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_error TEXT,
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS llm_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT REFERENCES events(event_id) ON DELETE SET NULL,
    intervention_id BIGINT REFERENCES interventions(id) ON DELETE SET NULL,
    task_kind TEXT NOT NULL,
    model TEXT NOT NULL,
    input_tokens INTEGER NOT NULL CHECK (input_tokens >= 0),
    output_tokens INTEGER NOT NULL CHECK (output_tokens >= 0),
    cached_tokens INTEGER CHECK (cached_tokens IS NULL OR cached_tokens >= 0),
    estimated_cost_usd NUMERIC(16, 8) NOT NULL DEFAULT 0 CHECK (estimated_cost_usd >= 0),
    latency_ms INTEGER NOT NULL CHECK (latency_ms >= 0),
    success BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_messages_chat_created ON messages (chat_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_expires_at ON messages (expires_at) WHERE expires_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_events_pending ON events (available_at, created_at) WHERE status IN ('pending', 'retry');
CREATE INDEX IF NOT EXISTS idx_events_scope_created ON events (scope_type, scope_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_memory_cards_scope_status ON memory_cards (scope_type, scope_id, status);
CREATE INDEX IF NOT EXISTS idx_memory_cards_scope_type ON memory_cards (scope_type, scope_id, memory_type);
CREATE INDEX IF NOT EXISTS idx_memory_cards_subject_user ON memory_cards (subject_user_id) WHERE subject_user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_memory_relations_scope ON memory_relations (scope_type, scope_id);
CREATE INDEX IF NOT EXISTS idx_tasks_scope_status ON tasks (scope_type, scope_id, status);
CREATE INDEX IF NOT EXISTS idx_reminders_pending ON reminders (due_at) WHERE status IN ('pending', 'retry');
CREATE INDEX IF NOT EXISTS idx_reminders_scope_status ON reminders (scope_type, scope_id, status);
CREATE INDEX IF NOT EXISTS idx_interventions_scope_created ON interventions (scope_type, scope_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_feedback_intervention ON feedback_events (intervention_id) WHERE intervention_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_outbox_pending ON outbox (available_at, created_at) WHERE status IN ('pending', 'retry');
CREATE INDEX IF NOT EXISTS idx_llm_usage_event ON llm_usage (event_id) WHERE event_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_llm_usage_created ON llm_usage (created_at DESC);
